### ISSUE TITLE
Different data over different pins

### ISSUE THREAD

**Issue by kleurbleur** [hpwit/I2SClocklessLedDriver#10]
The example does work but seems to mirror the output from the code. I guess that's what that parallel means in the description. In another issue here it is mentioned that you do support different data over different pins, but I'm curious how. I'm trying to make an ArtNet controller and this lib seems to be the most efficient out there. 

In my case I need to send data over over ~2400 leds, quite a big distance and I need to be able to address all of them individually. That's why the different outputs. 

Check here for my code so far: https://pastebin.com/qFUJRCv4

**Comment by hpwit** [comment]
Hello
What do you mean 'by mirror the output from the code ?' is that that all the leds display the same content on different pins ?
The driver supports different data over different pins

in your code I don't understand
'int led = i + (universe - startUniverse) * (previousDataLength / channelsPerLed);'
either all your universes have the same size and you do 
led =I+(universe-startUniverse)*Size;
or you assume all the data arrive sequentially and it's  more
led  =I+previousdatalength;
and you have previousdatalength+=length
but then it will depend of you tool some art net tool always put a size of 512 even without broadcasting 512 channels

I would do some serial.print to display some information to see what you are receiving

PS: could you put the define NUMSTRIPS and NUM_LEDS_PER_STRP before the include "I2SClocklessLedDriver"

Let me know how I can help you

question: which tool are you using to create the art net packets ?
 you can have a look at my take of the artnet Library

https://github.com/hpwit/artnetESP32

**Comment by kleurbleur** [comment]
Yeah, the pins display the same output on both pins. In the rgbw example as well as my code.

That piece of code makes sure that the leds numbering goes up per universe and comes from the example of the art net library I'm using. See here: https://github.com/natcl/Artnet

Your take on artnet seems very interesting but it seems to work only with FastLed? I have RGBW strips only and got problems getting those to work.

**Comment by hpwit** [comment]
Hello
Could you first try my example with RGBW putting NUMSTRIPS and NUM_LEDS_PER_STRIP to you setting to see if that works already. if not  I will need to check

The library I wrote can work with my driver  I just need to adapt to take into account RGBW leds
