### ISSUE TITLE
How to I2SClocklessLedDriver with WLED source code.

### ISSUE THREAD

**Issue by jagspaul** [hpwit/I2SClocklessLedDriver#15]
I want to use I2SClocklessLedDriver with WLED source code.
It is found that WLED uses Fastled driver and Fastled as I2S Clockless LedDriver but this i2s driver does not support FULL_DMA_BUFFER.

In this regard you are requested to help me how can I use your I2SClocklessLedDriver (https://github.com/hpwit/I2SClocklessLedDriver) FULL_DMA_BUFFER wit WLED source to build my custom WLED firmware.

Tanks & Regards
Jags

**Comment by hpwit** [comment]
Hello
Ido not know WLED but it should be possible to replace fastLED by the driver but I would need to look at it.
I thought WELD was using its own driver.
I will have a look

**Comment by netmindz** [comment]
WLED does not use FastLED for it's output, it uses NeoPixelBus

It's on my to-do list to try adding both FastLED and this driver as options to see which is most performant and reliable

**Comment by hpwit** [comment]
Hello
Let me know how it goes and if you need some help with the integration. 
Interesting to know if it will work.
