### ISSUE TITLE
ESP-IDF Support

### ISSUE THREAD

**Issue by parksj10** [hpwit/I2SClocklessLedDriver#16]
Very cool project first of all! thanks for sharing.

I read [here](https://old.reddit.com/r/FastLED/comments/mzic57/esp32_sk6812_fastest_method/i657dkj/) that this library supports ESP-idf, however, I'm having trouble getting the compiler to recognize your .h properly (perhaps because it's actually C++, not C, e.g. `cstring` doesn't seem to be available). Do you happen to have a basic example of your library integrated with esp-idf

**Comment by hpwit** [comment]
hello
I will look at it since the version 5 of esp-idf I need to make changes I will try to look at it asap
Yves

**Comment by parksj10** [comment]
ahhh thanks! I'm actually on IDF 4.4.4 and it still seems to not want to work, I'm going to keep fiddling as well. I'll post a minimum reproducible example if I can get it working

**Comment by parksj10** [comment]
So more digging, seems like the `.h` was getting treated as a `C` compiled file, which I remedied via 
```
#ifdef __cplusplus
extern "C++"
{
#endif
```
however, it seems like there are other references in your code to `Arduino.h`... is it required to run an Arduino core in esp-idf to get your program to work?

**Comment by netmindz** [comment]
Who is going to get IDF v5 support first, you or FastLED? 😜

**Comment by hpwit** [comment]
Normally it should be already compatible with espidf v5. I have made the necessary change for the virtualLed I will check for this one
