### ISSUE TITLE
License of library

### ISSUE THREAD

**Issue by shirogeek** [hpwit/I2SClocklessLedDriver#17]
Hi,

I am making a product and would like to use your library. I do not see however the license for your open source work so that I can know my obligations. 

Thanks

**Comment by hpwit** [comment]
Hello
Thank you for your interest in my library. 

Indeed I need to put this in my library. 
I am targeting a free usage of the library even for commercial products. 
I will require the disclosure that you are using my library. 
If you have an idea of a license that can stipulate this this will be nice. 
Can I ask you more about your product 
You can write to me bazin.yves at gmail. 
Yves

**Comment by shirogeek** [comment]
Hi Yves,

I would propose to use MIT license as it is most friendly for commercial purposes. You would still get credit but the person using your library is not obliged to make code open source. Otherwise, LGPL3 is possible, you would still get credit and the developer must make the code open source. As far as I am concerned, I only use MIT code in my products because I do not wish to maintain open source code. I make hardware and sell hardware. Credit of course is still given.

My product is just another fancy LED driver based on ESP32 with wifi :) I will keep you updated when I finish the development and start branding if you are interested !

Best Regards

**Comment by hpwit** [comment]
Hello
I will do this asap and use the MIT license model.
