### ISSUE TITLE
Missing Math.h

### ISSUE THREAD

**Issue by netmindz** [hpwit/I2SClocklessLedDriver#21]
.pio/libdeps/esp32-c6-devkitc-1/I2SClocklessLedDriver/src/I2SClocklessLedDriver.h:31:10: fatal error: Math.h: No such file or directory

**Comment by hpwit** [comment]
Try with 
math.h instead of Math.h
Let me know 
Yves

**Comment by netmindz** [comment]
Yeah it looks like it should be all lowercase
