### ISSUE TITLE
Wont compile with V3.0.0 ESP32 Libs

### ISSUE THREAD

**Issue by leonyuhanov** [hpwit/I2SClocklessLedDriver#23]
Heya
For this to work with V3.0.0+ Arduino ESP32 framework, add the following lines to the .H file

````
#include "soc/gpio_struct.h"	
#include "soc/gpio_periph.h"	
#include "rom/gpio.h"			
````

**Comment by hpwit** [comment]
Indeed I have made the update for the virtual driver but not for the regular one. Thank you pointing that out 
Yves

**Comment by hpwit** [comment]
push made

**Comment by leonyuhanov** [comment]
Yei!
