### ISSUE TITLE
Tried with Esp32 s2 not getting correct output

### ISSUE THREAD

**Issue by ScobbyDoo** [hpwit/I2SClocklessLedDriver#3]
I tried with i2s0 (esp32s2 dont have i2s1) with one change in library **clka_en** to **clk_en** as warning in compiler & found some hint on Google

Do you have any idea to drive on esp32s2

**Comment by hpwit** [comment]
I have never tried with esp32 s2 I think it will need a rework I need to look at it

**Comment by ScobbyDoo** [comment]
What about  esp32's i2s0?
Is it possible  to drive through  i2s0 instead of i2s1?

**Comment by hpwit** [comment]
The code is using i2s0 not i2s1
