### ISSUE TITLE
Broken DMA option

### ISSUE THREAD

**Issue by michielbrink** [hpwit/I2SClocklessLedDriver#8]
Hi Hpwit,

I am looking to the library you made and it looks great! I also really like your readme approach. :)
After playing with the default mode on an ESP32 my next step is to use the DMA mode (SK6812). I found some bugs when trying to use it.

1. While compiling the full buffer loop example I got the following error:
`I2SClocklessLedDriver.h:391:34: error: no matching function for call to 'I2SClocklessLedDriver::showPixelsFirstTranspose()'`
To fix this I renamed showPixelsFirstTranspose to showPixelsFirstTranpose. (Without s in Transpose)

2. After this I got the following error:
```
I2SClocklessLedDriver.h:453:112: error: cannot convert 'uint8_t*' {aka 'unsigned char*'} to 'uint16_t*' {aka 'short unsigned int*'}
             loadAndTranspose(leds, num_led_per_strip, num_strips, _offsetDisplay, DMABuffersTransposed[j + 1]->buffer, j, __green_map, __red_map, __blue_map, __white_map, nb_components, p_g, p_r, p_b);
```

I fixed this by adding (uint16_t *) in front of DMABuffersTransposed in this argument. (Line 453)

3. Now the example compiles. But now the ESP32 (WT32-S1) stays rebooting.It looks like the DMA is doing something strange.

Did you ever got this working? Or is this piece of code never finished?

**Comment by hpwit** [comment]
Hello
thank you for pointing that out.
Indeed that is strange because I have tested all the code for the FULL_DMA let me check the version I have on my laptop.
I know I have made  a change when adding the hardware scrolling and sprite to the fulldmabuffer
try this version 
https://github.com/hpwit/I2SClocklessLedDriver/tree/87a67af8b39090fe254a45308c72386e11bc85a6
and let me know if you have issues
i will check why I have this issue maybe a missing commit

**Comment by michielbrink** [comment]
Thank you for your quick reply. Currently I am really busy and I could not find time to test it yet. My planning is to have a look on it in the weekend.

I will let your know how it went. :)

**Comment by costyn** [comment]
Hello Yves, I was facing a similar issue as Michiel. I thought the showPixelsFirstTranpose without the second 's' was a copy/paste/replace typo, changed them back to showPixelsFirstTranspose (fixed the spelling error), and used his nr 3 fix to bypass the issue. 

Firmware running both on M5 Atom and ESP32 DevKitC without crashing.

**Comment by hpwit** [comment]
Hello hello
How are you ? Long time no see ;)
Have you tried the previous version as I have suggested ?

**Comment by costyn** [comment]
Hello, yes long time :) Doing allright 👍  I didn't try the previous version as this one worked ok for me. If you want I can try previous commit

**Comment by michielbrink** [comment]
I finally got time to test it.  :)
The version you sended in this thread works great and plug and play! I am really happy with this :)

To summarize: 
Dma works with this version and dma does not work with the main repo version.

For me you can close this thread now as it looks like it is solved. Thank you very much :)

Greatings,
Michiel

**Comment by hpwit** [comment]
Great to hear !! My I ask what is your build about and why did you choose the full dma rather than the usual one ?

**Comment by michielbrink** [comment]
By also using the ArtNet library, I made a tiny program to control 360 RGBW sk6812 leds :)

The ArtNet library outputs an array of values. After receiving data, I am doing a memcpy to the array used in driver.initled().

**Comment by hpwit** [comment]
I have made a version of the artnet library also. 
but 360 pixels you do not have too many issues I guess

**Comment by michielbrink** [comment]
Indeed, till now it works great!  :)

**Comment by hpwit** [comment]
> Hello, yes long time :) Doing allright 👍 I didn't try the previous version as this one worked ok for me. If you want I can try previous commit

@costyn great to hear !!! are you working on something nice ?

**Comment by hpwit** [comment]
@costyn talk to you soon

**Comment by michielbrink** [comment]
I finally got time to test it.  :)
The version you sended in this thread works great and plug and play! I am really happy with this :)

To summarize:
Dma works with this version and dma does not work with the main repo version.

For me you can close this thread now as it looks like it is solved. Thank you very much :)

Greatings,
Michiel

________________________________

**Comment by hpwit** [comment]
good to hear !!
I will add this correction in the mail repo
BTW I am always interested in how the people are building with my libraires. If you can share that will be nice to explain your project
thank you
rgds
Yves
